site_name: Provincie Zeeland Workshops
repo_url: https://github.com/ProvincieZeeland/Remoto-workshop-tekst-website
repo_name: Provincie Zeeland Workshops
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections 
    - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt 
  palette:
    - scheme: default
      primary: deep blue
      accent: blue grey

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Fijnstof:
    - Introductie: fijnstof/start.md
    - Code schrijven:
      - Eerste test: fijnstof/first-test.md
      - Hallo wereld: fijnstof/first-code.md
      - Herhalingen: fijnstof/while-loop.md
      - Als, dan, wat: fijnstof/if-else.md
      - Lampje knipperen: fijnstof/blink.md
    - Fijnstof meten:
      - Wat is fijnstof: fijnstof/pm.md
      - Praten met de sensor: fijnstof/uart.md
      - Een meting doen: fijnstof/pm-measurement.md
    - Online verbinding:
        - Wat is LoRa(WAN): fijnstof/lorawan.md
        - LoRaWAN module: fijnstof/rak3172.md
    - De laatste stap:
        - Online je meting versturen: fijnstof/final-step.md

